### ISSUE TITLE
Works locally for me but not on production machine

### ISSUE THREAD

**Issue by JanSichula** [gabrieleromanato/jQuery-sessionStorage-shopping-cart#2]
Hello,

I have found this exploratory example to be of great interest but it is working properly only when I am   running it locally on my dev box. Once I move it to Heroku web server, it no longer remembers values that I input.

App is alive at https://blooming-hamlet-2394.herokuapp.com/.

My local setup Windows 8.1 Pro x64 + GoLang 1.4.2 + Visual Studio Code
My production setup: Heroku development dyno with Go 1.4.2 on Cedar 14 stack

Any advice will be greatly appreciated.

**Comment by gabrieleromanato** [comment]
Mixed Content: The page at 'https://blooming-hamlet-2394.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js'. This request has been blocked; the content must be served over HTTPS.

Use HTTPS to load jQuery:

https://ajax.googleapis.com/ajax/libs/jquery/2.0.3/jquery.min.js
